### ISSUE TITLE
Cannot build on windows (Lwt 2.4.5)

### ISSUE THREAD

**Issue by braibant** [ocsigen/lwt#84]
Here is the log according to opam (but I also get this error if I compile "by hand").

```
===== ERROR while installing lwt.2.4.5 =====
# opam-version 1.1.2 (007c9356a3129fced7c3d7016216839013dbfb90)
# os           cygwin
# command      make build
# path         /home/vagrant/.opam/system/build/lwt.2.4.5
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/vagrant/.opam/system/build/lwt.2.4.5/lwt-1788-ffb3fd.env
# stdout-file  /home/vagrant/.opam/system/build/lwt.2.4.5/lwt-1788-ffb3fd.out
# stderr-file  /home/vagrant/.opam/system/build/lwt.2.4.5/lwt-1788-ffb3fd.err
### stdout ###
# ...[truncated]
#             ^
# src/unix/lwt_unix_stubs.c:1136:3: warning: implicit declaration of function ‘sigaltstack’ [-Wimplicit-function-declaration]
#    sigaltstack(&new_stack, &old_stack);
#    ^
# src/unix/lwt_unix_stubs.c:1142:21: error: ‘SA_ONSTACK’ undeclared (first use in this function)
#    new_sa.sa_flags = SA_ONSTACK;
#                      ^
# src/unix/lwt_unix_stubs.c:1142:21: note: each undeclared identifier is reported only once for each function it appears in
# Command exited with code 2.
# Makefile:27: recipe for target 'build' failed
### stderr ###
# ocamlfind: Package `wikidoc' not found
# E: Failure("Command ''/usr/bin/ocamlbuild' syntax/optcomp.cma syntax/optcomp.cmxa syntax/optcomp.a src/core/lwt.cma src/core/lwt.cmxa src/core/lwt.a src/logger/lwt-log.cma src/logger/lwt-log.cmxa src/logger/lwt-log.a src/unix/liblwt-unix_stubs.a src/unix/dlllwt-unix_stubs.so src/unix/lwt-unix.cma src/unix/lwt-unix.cmxa src/unix/lwt-unix.a src/simple_top/lwt-simple-top.cma src/simple_top/lwt-simple...[truncated]
# make: *** [build] Error 1
 
'opam install lwt' failed.
```

**Comment by msprotz** [comment]
I'm getting a different error here (not enough quoting).

```
E: Failure("Command 'C:\\OCaml\\bin\\ocamlbuild.EXE -classic-display -no-log -no-links -install-lib-dir C:\\OCaml\\lib\\ocamlbuild -byte-plugin syntax/optcomp.cma syntax/optcomp.cmxa syntax/optcomp.a syntax/optcomp.cmxs src/core/lwt.cma src/core/lwt.cmxa src/core/lwt.a src/core/lwt.cmxs src/logger/lwt-log.cma src/logger/lwt-log.cmxa src/logger/lwt-log.a src/logger/lwt-log.cmxs src/unix/liblwt-unix_stubs.a src/unix/dlllwt-unix_stubs.dll src/unix/lwt-unix.cma src/unix/lwt-unix.cmxa src/unix/lwt-unix.a src/unix/lwt-unix.cmxs src/simple_top/lwt-simple-top.cma src/simple_top/lwt-simple-top.cmxa src/simple_top/lwt-simple-top.a src/simple_top/lwt-simple-top.cmxs src/react/lwt-react.cma src/react/lwt-react.cmxa src/react/lwt-react.a src/react/lwt-react.cmxs src/preemptive/lwt-preemptive.cma src/preemptive/lwt-preemptive.cmxa src/preemptive/lwt-preemptive.a src/preemptive/lwt-preemptive.cmxs src/extra/lwt-extra.cma src/extra/lwt-extra.cmxa src/extra/lwt-extra.a src/extra/lwt-extra.cmxs syntax/lwt-syntax.cma syntax/lwt-syntax.cmxa syntax/lwt-syntax.a syntax/lwt-syntax.cmxs syntax/lwt-syntax-options.cma syntax/lwt-syntax-options.cmxa syntax/lwt-syntax-options.a syntax/lwt-syntax-options.cmxs syntax/lwt-syntax-log.cma syntax/lwt-syntax-log.cmxa syntax/lwt-syntax-log.a syntax/lwt-syntax-log.cmxs examples/unix/logging.native examples/unix/relay.native examples/unix/parallelize.native -tag debug' terminated with error code 127")
```

(opam is a cygwin executable; ocaml is the native toolchain)

**Comment by aantron** [comment]
@braibant I believe this has been solved by Cygwin upstream, as pointed out by fdopen in the duplicate issue #173. Current Lwt [does build](https://ci.appveyor.com/project/aantron/lwt/build/93/job/wxco93cxoa5k1k9u) on Cygwin now.

@msprotz: This looks like a problem with something other than Lwt, I would guess OCamlbuild, but perhaps OPAM instead. Please check those projects, and let me know if you are still having this issue, if you think it is with Lwt, and you would like to resolve it :)

**Comment by msprotz** [comment]
Apparently I managed to install it eventually so we're good. Thanks for the reply!

~ jonathan
